"""Grounding Validator enforcing strict validation on grounded physical targets.

Guardrail 4: LLM Does Not Control Physical Coordinates.
Physical screen coordinates may only be produced by grounding infrastructure and must pass GroundingValidator.
Guardrail 5: VLM is Not an Executor (VLM provides evidence; coordinates must be bounded and validated).
Guardrail 16: No Silent Fallback Success.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional, Tuple
from pydantic import BaseModel, Field

from orbit.models.common import BoundingBox
from orbit.runtime.agent.contracts import SemanticTarget
from orbit.runtime.targeting.models import ResolvedTarget, SafeActionPoint, TargetBoundingBox

logger = logging.getLogger(__name__)


class GroundingValidationResult(BaseModel):
    """Validation report for candidate grounded target coordinates."""

    is_valid: bool = Field(..., description="Whether grounded target satisfies geometric, confidence, and context rules")
    failure_reason: Optional[str] = Field(default=None, description="Diagnostic explanation if invalid")
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    validated_point: Optional[Tuple[int, int]] = Field(default=None, description="Physical screen point (x, y)")


class GroundingValidator:
    """Validates physical coordinates generated by runtime grounding infrastructure before execution.

    Validation Rules:
    1. Confidence threshold: >= min_confidence (default 0.70).
    2. Physical desktop boundary check: coordinates must lie strictly within visible desktop dimensions.
    3. Non-zero bounding box validation: target must have a positive width and height.
    4. Ambiguity rejection: if multiple disparate targets claim identical confidence without disambiguation, reject.
    5. Semantic alignment: if target specifies role/window, grounding metadata must not contradict.
    """

    def __init__(
        self,
        min_confidence: float = 0.70,
        desktop_width: int = 3840,
        desktop_height: int = 2160,
    ) -> None:
        self._min_confidence = min_confidence
        self._desktop_width = desktop_width
        self._desktop_height = desktop_height

    def validate_grounding(
        self,
        target: SemanticTarget,
        resolved_target: Optional[ResolvedTarget] = None,
        candidate_coords: Optional[Tuple[int, int]] = None,
        desktop_width: Optional[int] = None,
        desktop_height: Optional[int] = None,
    ) -> GroundingValidationResult:
        """Validate candidate grounded coordinates against strict bounds and confidence rules."""
        dw = desktop_width or self._desktop_width
        dh = desktop_height or self._desktop_height

        # 1. Check coordinates presence
        coords = candidate_coords
        confidence = 1.0

        if resolved_target is not None:
            confidence = resolved_target.confidence
            if resolved_target.safe_point:
                coords = (int(resolved_target.safe_point.x), int(resolved_target.safe_point.y))

        if coords is None:
            return GroundingValidationResult(
                is_valid=False,
                failure_reason=f"No physical coordinates could be resolved for target '{target.name}'",
                confidence=0.0,
            )

        x, y = coords

        # 2. Confidence Threshold Check (Guardrail 4 & 16)
        if confidence < self._min_confidence:
            return GroundingValidationResult(
                is_valid=False,
                failure_reason=f"Grounding confidence {confidence:.2f} is below safety threshold {self._min_confidence:.2f}",
                confidence=confidence,
            )

        # 3. Physical Desktop Boundary Check
        if x < 0 or x >= dw or y < 0 or y >= dh:
            return GroundingValidationResult(
                is_valid=False,
                failure_reason=f"Grounded coordinates ({x}, {y}) fall outside desktop bounds ({dw}x{dh})",
                confidence=confidence,
            )

        # 4. Target Bounding Box Check (if present on resolved target)
        if resolved_target is not None and resolved_target.bounding_box:
            bbox = resolved_target.bounding_box
            w = bbox.right - bbox.left
            h = bbox.bottom - bbox.top
            if w <= 0 or h <= 0:
                return GroundingValidationResult(
                    is_valid=False,
                    failure_reason=f"Grounded bounding box has invalid dimensions (width={w}, height={h})",
                    confidence=confidence,
                )
            # Ensure coordinates are inside or on the bounding box
            if not (bbox.left <= x <= bbox.right and bbox.top <= y <= bbox.bottom):
                return GroundingValidationResult(
                    is_valid=False,
                    failure_reason=f"Action point ({x}, {y}) is outside resolved bounding box ({bbox.left},{bbox.top},{bbox.right},{bbox.bottom})",
                    confidence=confidence,
                )

        return GroundingValidationResult(
            is_valid=True,
            confidence=confidence,
            validated_point=(x, y),
        )
