"""Domain contracts and data models for the Cognitive Intent & Decision Engine subsystem."""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import uuid4
from pydantic import BaseModel, Field, field_validator

from orbit.runtime.task_completion.models import TaskCompletionStatus


class AbstractActionType(str, Enum):
    """Supported atomic/abstract actions generated by the Cognitive Decision Engine."""

    LAUNCH_APPLICATION = "LAUNCH_APPLICATION"
    FOCUS_WINDOW = "FOCUS_WINDOW"
    CLICK_ELEMENT = "CLICK_ELEMENT"
    TYPE_TEXT = "TYPE_TEXT"
    DRAW_STROKES = "DRAW_STROKES"
    SEND_HOTKEY = "SEND_HOTKEY"
    WAIT_SETTLE = "WAIT_SETTLE"
    COMPLETE_GOAL = "COMPLETE_GOAL"
    ABORT_UNACHIEVABLE = "ABORT_UNACHIEVABLE"


class OutcomeStatus(str, Enum):
    """Classification of action execution and outcome verification."""

    EFFECT_VERIFIED = "EFFECT_VERIFIED"
    EFFECT_UNVERIFIED = "EFFECT_UNVERIFIED"
    DISPATCH_FAILED = "DISPATCH_FAILED"
    RECOVERY_ATTEMPTED = "RECOVERY_ATTEMPTED"


class SemanticTarget(BaseModel):
    """Abstract semantic target specification.

    SAFETY INVARIANT:
    Physical screen coordinates (x, y) MUST NEVER originate from the Cognitive or LLM layer.
    Coordinates are generated exclusively at execution time by runtime perception/target locator.
    """

    name: Optional[str] = Field(default=None, description="Logical target label, button text, or window title")
    role: Optional[str] = Field(default=None, description="UI accessibility role (e.g. edit, button, canvas, window)")
    context: Optional[str] = Field(default=None, description="Surrounding application or window context")
    anchor: Optional[str] = Field(default=None, description="Spatial anchor or relative descriptor")


class ActionOutcomeContract(BaseModel):
    """Contract specifying the observable physical effect expected from an action."""

    expected_state_transition: str = Field(..., description="Description of expected state delta (e.g. window_focused, text_entered, canvas_modified)")
    verification_strategy: str = Field(default="WINDOW_FOCUS_OR_STATE", description="Strategy to verify outcome: WINDOW_FOCUS_OR_STATE, UIA_STATE, PIXEL_DIFF, OCR_MATCH")
    target_role: Optional[str] = Field(default=None, description="Expected active role")
    target_name: Optional[str] = Field(default=None, description="Expected active target name")


class AbstractAction(BaseModel):
    """An abstract action command emitted by the Cognitive Decision Engine."""

    action_id: str = Field(default_factory=lambda: f"act_{uuid4().hex[:8]}", description="Unique action identifier")
    action_type: AbstractActionType = Field(..., description="Action classification")
    target: Optional[SemanticTarget] = Field(default=None, description="Semantic target specification (NO coordinates)")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Semantic parameters only (e.g. text, shape, app_name)")
    outcome_contract: Optional[ActionOutcomeContract] = Field(default=None, description="Action-to-outcome contract")
    expected_effect: str = Field(default="", description="High-level expected effect description")
    rationale: str = Field(default="", description="Reasoning for choosing this specific action")

    @field_validator("parameters")
    @classmethod
    def validate_no_physical_coordinates(cls, v: Dict[str, Any]) -> Dict[str, Any]:
        """Enforce architectural invariant: LLM/Cognitive layer must never emit physical coordinates."""
        forbidden_keys = {"x", "y", "screen_x", "screen_y", "coord_x", "coord_y"}
        found = forbidden_keys.intersection(k.lower() for k in v.keys())
        if found:
            raise ValueError(f"Cognitive AbstractAction parameters must NOT contain physical coordinates: {found}")
        return v


class StructuredObjective(BaseModel):
    """Structured, epistemically grounded representation of user intent."""

    objective_id: str = Field(default_factory=lambda: f"obj_{uuid4().hex[:8]}", description="Unique objective identifier")
    raw_prompt: str = Field(..., description="Original user prompt verbatim")
    user_goal: str = Field(..., description="High-level summarized goal statement")
    end_condition: str = Field(..., description="Verifiable end state criteria (e.g. canvas_has_cube_drawing, notepad_contains_text)")
    target_entities: List[str] = Field(default_factory=list, description="Target applications, controls, files, or geometric shapes")
    constraints: List[str] = Field(default_factory=list, description="Negative or positive constraints and boundaries")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Extracted parameters (e.g. shape, text, app name)")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Timestamp of interpretation")


class CurrentStateObservation(BaseModel):
    """Immutable snapshot of the live desktop state observed by the perception layer."""

    observation_id: str = Field(default_factory=lambda: f"obs_{uuid4().hex[:8]}", description="Unique observation identifier")
    timestamp_utc: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Timestamp of observation")
    active_window_hwnd: Optional[int] = Field(default=None, description="HWND of foreground active window")
    active_window_title: Optional[str] = Field(default=None, description="Title of foreground active window")
    active_window_class: Optional[str] = Field(default=None, description="Win32 class name of active window")
    active_process_name: Optional[str] = Field(default=None, description="Process executable name of active window")
    visible_windows: List[Dict[str, Any]] = Field(default_factory=list, description="List of visible top-level windows")
    target_app_exists: bool = Field(default=False, description="Whether target application is currently running/open")
    target_app_is_active: bool = Field(default=False, description="Whether target application is the active foreground window")
    screen_summary: str = Field(default="", description="High-level text or perceptual summary of the screen")
    canvas_status: Optional[str] = Field(default=None, description="Status of target canvas if applicable: BLANK, NON_BLANK, UNKNOWN")
    ocr_tokens: List[str] = Field(default_factory=list, description="OCR text tokens recognized on screen")
    raw_evidence: Dict[str, Any] = Field(default_factory=dict, description="Raw sensory and accessibility telemetry")


class CognitiveDecision(BaseModel):
    """Output of a single reasoning cycle in the Cognitive Decision Engine.

    Stores structured, auditable decision fields without free-form unrestricted chain-of-thought.
    """

    decision_id: str = Field(default_factory=lambda: f"dec_{uuid4().hex[:8]}", description="Unique decision identifier")
    step_index: int = Field(default=0, description="0-indexed step iteration in the cognitive loop")
    decision_summary: str = Field(..., description="Auditable assessment of current state vs objective")
    decision_confidence: float = Field(default=1.0, description="Confidence in decision (0.0 to 1.0)")
    evidence_used: List[str] = Field(default_factory=list, description="Concrete observations used to make decision")
    expected_state_transition: str = Field(default="", description="Expected state transition resulting from this decision")
    reason_summary: str = Field(default="", description="Concise justification for the action")
    is_goal_satisfied: bool = Field(default=False, description="Whether current state satisfies objective end condition")
    escalated_to_llm: bool = Field(default=False, description="Whether this decision required LLM escalation")
    next_action: Optional[AbstractAction] = Field(default=None, description="The abstract action to execute next, or None if satisfied")


class ActionExecutionResult(BaseModel):
    """Execution and verification outcome of a single dispatched action.

    CRITICAL TRIPARTITE DISTINCTION:
    1. dispatch_success: Did the operating system / adapter accept the command?
    2. expected_effect_observed: Was the expected physical state transition verified?
    3. outcome_status: Verified vs Unverified vs Failed.
    """

    dispatch_success: bool = Field(..., description="Whether input command was accepted by OS/driver")
    expected_effect_observed: bool = Field(..., description="Whether expected observable state change was physically verified")
    outcome_status: OutcomeStatus = Field(..., description="Outcome classification")
    evidence: Dict[str, Any] = Field(default_factory=dict, description="Sensory evidence supporting outcome")
    observed_delta: Dict[str, Any] = Field(default_factory=dict, description="Observed change in system state")
    error_message: Optional[str] = Field(default=None, description="Error detail if action or verification failed")


class ExecutionBudget(BaseModel):
    """Progress-based execution budget preventing infinite loops and tracking meaningful state change."""

    max_total_actions: int = Field(default=50, description="Hard upper bound on total actions dispatched")
    max_repeated_actions_without_progress: int = Field(default=3, description="Max consecutive identical actions without state progress")
    max_recoveries_per_transition: int = Field(default=2, description="Max recovery attempts for a single state transition")
    max_llm_escalations: int = Field(default=5, description="Max times LLM can be invoked for decision escalation")
    no_progress_timeout_sec: float = Field(default=30.0, description="Timeout if no forward state progress is made")


class CognitiveStepResult(BaseModel):
    """Audit record of an executed cognitive loop iteration."""

    step_index: int = Field(..., description="Iteration number")
    decision: CognitiveDecision = Field(..., description="Cognitive decision made in this step")
    action_dispatched: Optional[AbstractAction] = Field(default=None, description="Action sent to executor")
    execution_result: Optional[ActionExecutionResult] = Field(default=None, description="Immediate action execution and outcome verification")
    post_observation: Optional[CurrentStateObservation] = Field(default=None, description="State observed after action execution")
    state_progress_detected: bool = Field(default=False, description="Whether this step moved the system state closer to the goal")
    duration_ms: float = Field(default=0.0, description="Execution duration of this step in milliseconds")

    @property
    def action_success(self) -> bool:
        return bool(self.execution_result and self.execution_result.dispatch_success)

    @property
    def outcome_verified(self) -> bool:
        return bool(self.execution_result and self.execution_result.expected_effect_observed)


class CognitiveExecutionResult(BaseModel):
    """End-to-end outcome of a cognitive execution loop run."""

    task_id: str = Field(..., description="Task identifier")
    objective: StructuredObjective = Field(..., description="Structured objective that guided execution")
    is_success: bool = Field(default=False, description="Whether the task objective was successfully satisfied and verified")
    total_steps: int = Field(default=0, description="Total cognitive iterations executed")
    step_history: List[CognitiveStepResult] = Field(default_factory=list, description="Chronological record of every step")
    final_status: TaskCompletionStatus = Field(default=TaskCompletionStatus.FAILED, description="Terminal task status")
    failure_reason: Optional[str] = Field(default=None, description="Explanation of failure if not successful")
    failure_code: Optional[str] = Field(default=None, description="Error code if failed")
    elapsed_duration_ms: float = Field(default=0.0, description="Total wall-clock duration in milliseconds")
