"""Semantic Feasibility Evaluator.

INVARIANT (ASTRA Dimension 3 & 5): Semantic feasibility evaluates candidate plans produced
by the Planner BEFORE a plan directive is selected and emitted.
Ordering:
  Preflight (RuntimeFeasibility) -> Planner Candidate Generation -> Semantic Feasibility -> Plan Selection -> PlanDirective -> PrimitiveComposer
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional, Set, Tuple
from uuid import uuid4
from pydantic import BaseModel, Field

from orbit.runtime.agent.contracts import (
    AbstractActionType,
    ActionOutcomeContract,
    SemanticTarget,
)
from orbit.runtime.world_model.model import AgentWorldModel

logger = logging.getLogger(__name__)


class CandidatePlan(BaseModel):
    """A candidate strategy / primitive sequence generated by the Planner for an active subgoal."""

    candidate_id: str = Field(default_factory=lambda: f"cand_{uuid4().hex[:8]}")
    subgoal_id: str
    intent_strategy: str = Field(default="GUI_INTERACTIVE", description="e.g. GUI_INTERACTIVE, CANVAS_RENDERING, ENVIRONMENT_INTERFACE")
    proposed_primitives: List[AbstractActionType] = Field(default_factory=list)
    targets: List[SemanticTarget] = Field(default_factory=list)
    expected_outcome: ActionOutcomeContract
    estimated_complexity: int = Field(default=1, ge=1)
    creative_payload: Optional[Dict[str, Any]] = None
    rationale: str = Field(default="")


class SemanticFeasibilityReport(BaseModel):
    """Detailed audit report of semantic feasibility assessment across candidates."""

    is_feasible: bool
    approved_candidate_id: Optional[str] = None
    rejection_reasons: List[str] = Field(default_factory=list)
    candidate_scores: Dict[str, float] = Field(default_factory=dict)
    best_score: float = Field(default=0.0)


class SemanticFeasibilityEvaluator:
    """Evaluates candidate plans generated by the Planner prior to PlanDirective emission."""

    def __init__(self, min_feasibility_threshold: float = 0.5) -> None:
        self._threshold = min_feasibility_threshold

    def evaluate_candidate(
        self,
        candidate: CandidatePlan,
        world_model: AgentWorldModel,
    ) -> Tuple[float, List[str]]:
        """Score a single candidate plan from 0.0 to 1.0. Returns (score, rejection_reasons)."""
        rejection_reasons: List[str] = []
        score: float = 1.0

        # 1. Reject empty plans
        if not candidate.proposed_primitives:
            return 0.0, ["Candidate plan proposes zero primitives"]

        # 2. Check for past failed sequences in WorldModel
        if world_model.failed_primitive_sequences:
            prop_names = [p.value for p in candidate.proposed_primitives]
            for failed_rec in world_model.failed_primitive_sequences:
                if failed_rec.primitive_sequence == prop_names:
                    score -= 0.6
                    rejection_reasons.append(
                        f"Sequence matches recently failed sequence on sub-goal '{failed_rec.sub_goal_title}'"
                    )

        # 3. Canvas rendering checks (ASTRA-6 Semantic Feasibility Authority)
        if AbstractActionType.DRAW_STROKES in candidate.proposed_primitives:
            payload = candidate.creative_payload or {}
            shape = str(payload.get("shape", "")).lower()
            raw_prompt = str(payload.get("raw_prompt", payload.get("prompt", ""))).lower()
            unfeasible_keywords = ["portrait", "portrait_of_boy", "face", "person", "human", "realistic", "landscape", "photo of"]

            if any(k in shape for k in unfeasible_keywords) or any(k in raw_prompt for k in ["portrait", "photo of"]):
                return 0.0, [
                    f"Goal is NOT FEASIBLY EXECUTABLE (unsupported complex drawing shape '{shape or 'complex'}' exceeds vector stroke drawing capabilities)"
                ]

            if not payload or "strokes" not in payload:
                score -= 0.5
                rejection_reasons.append("DRAW_STROKES primitive missing normalized stroke payload")
            else:
                strokes = payload.get("strokes", [])
                # Verify coordinates are normalized in [0, 1]
                for stroke in strokes:
                    for pt in stroke:
                        if isinstance(pt, (list, tuple)) and len(pt) == 2:
                            u, v = pt[0], pt[1]
                            if not (0.0 <= u <= 1.0 and 0.0 <= v <= 1.0):
                                return 0.0, [f"Invalid unnormalized stroke coordinate ({u}, {v})"]
                        else:
                            return 0.0, [f"Invalid stroke format {pt}"]

        # 4. Target validity checks
        for target in candidate.targets:
            if not target.name and not target.role and not target.text_hint:
                score -= 0.3
                rejection_reasons.append(f"Candidate target has zero identifying attributes")

        # 5. Complexity penalty
        if candidate.estimated_complexity > 15:
            score -= 0.2

        score = max(0.0, min(1.0, score))
        return score, rejection_reasons

    def select_feasible_plan(
        self,
        candidates: List[CandidatePlan],
        world_model: AgentWorldModel,
    ) -> Tuple[Optional[CandidatePlan], SemanticFeasibilityReport]:
        """Evaluate all candidate plans and select the highest-scoring feasible candidate."""
        if not candidates:
            return None, SemanticFeasibilityReport(
                is_feasible=False,
                rejection_reasons=["No candidate plans provided by planner"],
            )

        candidate_scores: Dict[str, float] = {}
        all_rejections: List[str] = []
        best_candidate: Optional[CandidatePlan] = None
        best_score: float = -1.0

        for cand in candidates:
            score, rejections = self.evaluate_candidate(cand, world_model)
            candidate_scores[cand.candidate_id] = score
            if rejections:
                all_rejections.extend(rejections)

            if score >= self._threshold and score > best_score:
                best_score = score
                best_candidate = cand

        is_feasible = best_candidate is not None
        return best_candidate, SemanticFeasibilityReport(
            is_feasible=is_feasible,
            approved_candidate_id=best_candidate.candidate_id if best_candidate else None,
            rejection_reasons=all_rejections if not is_feasible else [],
            candidate_scores=candidate_scores,
            best_score=max(0.0, best_score),
        )


__all__ = [
    "CandidatePlan",
    "SemanticFeasibilityEvaluator",
    "SemanticFeasibilityReport",
]
